Fix error when creating TimeoutException
We need to have a valid format specifier. Currently this produces:

ValueError: unsupported format character 'w' (0x77) at index 50

[0] http://logs.openstack.org/94/561194/5/check/designate-base/401ff70/testr_results.html.gz

Change-Id: Ibb500c3ed26e23e7770901fa85e6e5bdbb15d741